### ISSUE TITLE
Julia: Quarto Publish Action no longer works with Jupyter installed by `Conda.jl`

### ISSUE THREAD

**Issue by eliascarv** [quarto-dev/quarto-actions#98]
I had to change the Jupyter installation method in our Action from [Conda.jl](https://github.com/JuliaPy/Conda.jl) to Python Pip because the action `quarto-dev/quarto-actions/publish@v2` is no longer working with the first method. 

Below is the PR of this change:
https://github.com/JuliaEarth/geospatial-data-science-with-julia/pull/17

This Action was working normally, but stopped working in the last few commits.

This is the error that occurs when Jupyter is installed by [Conda.jl](https://github.com/JuliaPy/Conda.jl):
![Captura de tela de 2024-02-02 11-34-47](https://github.com/quarto-dev/quarto-actions/assets/73039601/ed48bd05-116b-425a-94ff-1bda6fc6a44b)

Maybe `quarto-dev/quarto-actions/publish@v2` can no longer find the Julia kernel when Jupyter is installed by [Conda.jl](https://github.com/JuliaPy/Conda.jl)?

**Comment by cderv** [comment]
This quarto action is not setting up any dependencies. The quarto publish action will only do `quarto render` and `quarto publish`

According to your screenshot error, the rendering fails because the Jupyter kernel julia-1.10 is not found. 

Does the rendering work locally with the same setup ? 

I'll have a look in your action. THis is either a configuration problem, and somehow an issue with Quarto render and Julia 1.10 but it works work me locally and in our test suits

**Comment by cderv** [comment]
Looking at your repo log it seems the the update to 1.3.450 to latest 1.4.459 caused the issue. 

Somehow the kernel is indeed not seen; I don't think this is action specific - this would mean that `quarto` CLI itself would have the problem. 

We need to create an environment to reproduce this

**Comment by eliascarv** [comment]
Thanks for looking at this issue @cderv.

**Comment by cderv** [comment]
I opened an issue upstream in quarto-cli. Thanks again for the report! We'll follow there.
